db.pool.size=3
db.path=D:/Programming/java/currency_exchange/data/main.db
schema.path=D:/Programming/java/currency_exchange/src/main/resources/db/schema.sql
seed.path=D:/Programming/java/currency_exchange/src/main/resources/db/seed.sql